### ISSUE TITLE
[Feature] Finer grained access control based on siteaccess

### ISSUE THREAD

**Issue by wizhippo** [netgen-layouts/layouts-ezplatform#5]
Being able to restrict a role to mapping to a siteaccess would be useful.

An admin could create the layouts.

Another role could have 'mapping' only permission with siteaccess like limitation so they could assign layouts to their content without the ability to create new layouts.

**Comment by emodric** [comment]
Advanced access control is currently being developed, similar to how eZ Platform handles permissions. It will not, however, end up in open source version, since it will only be part of our enterprise offering.

What open source version will end up having is different Symfony role names for different actions in the system, so you will have a chance to roll your own custom solution for permissions for some or all parts of the system.
